### PR TITLE
Add Container App support for ADO and Github Runners

### PR DESCRIPTION
**Pull request by BlakeWills-BJSS**
## Description

This PR adds support for running Github runners and ADO agents as Azure Container Apps.

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by BlakeWills-BJSS** [comment]
@microsoft-github-policy-service agree company="BJSS"

**Comment by BlakeWills-BJSS** [comment]
@jaredfholgate - I've had a crack at porting over our Container App code into this module. There's still a few tweaks I want to make to ensure the APIs between Github and ADO are the same (especially around how we handle the KEDA metadata, see the Github submodule for how I want to do it), but I'd massively appreciate it if you could double check I'm heading in the right direction.

This repo seems to be a wrapper for multiple types of runners (Container Instances, Container Apps, VMSS, etc) so I've created submodules for the container apps. I think this could get very large, very quickly, so we might want to consider splitting this out into a repo per type?

Let me know what you think.

**Comment by jaredfholgate** [comment]
Hi @BlakeWills-BJSS. You must think I am a terrible person for ignoring you for this long! Well the good new this has finally made it to the top of my priority list and will be an important part of expanding the Accelerators to encompass Application Landing Zones. As such, I am going to pick this up on Monday and start working on it.

**Comment by jaredfholgate** [comment]
Replacing with local branch and #39 to reduce some overhead for me.

**Pull request closed without merging**
